### PR TITLE
Micro reddit ready to review

### PR DESCRIPTION
**Pull request by ahmetbozaci**
Dear TSE,

In this project
We created three tables **"post, comment, user"** and they are association with each other.

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Change Requested 💀 

**Hello Team,** 

You have done a great job so far. Your project is almost done. Please make the following change to get approval on this project.  🌮 

- [ ] Please add tests in your project for the models you have added. 

In the case of any question please reach out to me on slack at @arslanbisharat. ☎️ : 

**Best,
Arslan Bisharat** 😄

**Comment by ahmetbozaci** [comment]
Dear TSE
This project requirements are clear. It doesn't want rspec test file. I looked my other teammate project too. No one create test file.
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/

**Comment by arslanbisharat** [comment]
Hello Team,
Please give me sometime to review this. I have requested my other fellow
TSEs to look into this matter. I apologise for the inconvenience I caused.
While you are waiting, you can start work on next project or work on
professionalism skill.

Again, I am sorry.

Best
Arslan Bisharat

**Review by rindrajosia — APPROVED** [review]
**Status 100 Approved**
Hi!!
You did a very good job.
The repository contains a descriptive readme. You just need to restructure the following line in your readme.
Before this line: `Migrate the database rails db:migrate`
Add this: `To create database rails db:create`

**This  :+1:   is from me you can go ahead.**

:four_leaf_clover:  **Happy Coding** :four_leaf_clover: 

**Rindra Josia**

**Comment by arslanbisharat** [comment]
@team, I Am sorry. I confirmed with Full-Time TSEs and you are not required to add tests here. 
Please forgive me for this mistake. 

Best,
Arslan Bisharat

**Pull request merged**
